spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
server:
  port: 8888
